python_modules/ascan/ascan/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from scan.views import index

urlpatterns = [
    path('', index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('scan/', include('scan.urls')),
    path('manager/', include('manager.urls')),
    path('bg/', include('bg.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

python_modules/ascan/bg/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('join/', views.join, name='join'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('activation_resend/', views.activation_resend, name='activation_resend'),
    path('sug/', views.autosuggest, name='sug'),
    path('mysearches/', views.SearchesList.as_view(), name='mysearches'),
    path('userprofile/', views.userprofile, name='userprofile'),
    path('delete_record/', views.deleteRecord, name='deleterecord'),
]

python_modules/ascan/scan/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('crawl/', views.crawl, name='crawl'),
    path('search/', views.search, name='search'),
]

python_modules/ascan/scan/forms.py
from django import forms
from django.db.models import Count
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Row, Column, HTML, Field
from crispy_forms.bootstrap import InlineCheckboxes

from scan.models import Site, Tag

class PublicScanForm(forms.Form):
    scan_query = forms.CharField(label='Search for')
    query_tags = forms.ModelMultipleChoiceField(Tag.objects.annotate(Count('site_links')).order_by(
        '-site_links__count').all(),
        label='If you want, limit to these tags...', to_field_name='name', required=False)
    query_sites = forms.ModelMultipleChoiceField(Site.objects.annotate(
        Count('scraperequest')).order_by('-scraperequest__count').all(),
        label='...and/or these sites', to_field_name='site_name', required=False)
    minimal_level = forms.ChoiceField(
            label='Minimal trustworthiness level',
            choices=[(x, x) for x in ['spam', 'community', 'respected', 'base']],
            initial='community')
    tab = forms.CharField(required=False) # the rule tab to show
    rule = forms.CharField(required=False) # the string rule, overrides the tab in terms of rule

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.disable_csrf = True # not desirable for the scan form
        self.helper.layout = Layout(
                Div('scan_query', css_class='typeahead'),
                # NOTE We have a custom template to accomodate list.js needs with the "list" class
                # and adding an invisible span with actual option text (bootstrap moves the label
                # text to ::before, ::after)
                Row(Column(InlineCheckboxes('query_tags', css_class='list', style='max-height: 200px',
                    template='widgets/form_searchable_multiplechoicefield.html')),
                    Column(InlineCheckboxes('query_sites', css_class='list', style='max-height: 200px',
                        template='widgets/form_searchable_multiplechoicefield.html'))),
                Row(Column('minimal_level')),
                HTML('<button id="search-button" type="submit" class="btn btn-primary btn-lg">Search the index</button>'
                    '{% if can_scan %} '
                    '<button id="scan-button" name="is_scan" value="true" type="submit" class="btn btn-primary btn-lg">Scan the Web</button>'
                    '{% endif %}'))

# NOTE it's important to make both forms compatible, to transfer the one from the main page into
# the index results
class EditableScanForm(forms.Form):
    """
    The form visible with the index result, where the user can refine their query.
    """
    scan_query = forms.CharField(label='Search for')
    query_tags = forms.ModelMultipleChoiceField(Tag.objects.annotate(Count('site_links')).order_by(
        '-site_links__count').all(),
        label='Tags', to_field_name='name', required=False)
    query_sites = forms.ModelMultipleChoiceField(Site.objects.annotate(
        Count('scraperequest')).order_by('-scraperequest__count').all(),
        label='Sites', to_field_name='site_name', required=False)
    minimal_level = forms.ChoiceField(
            label='Minimal level',
            choices=[(x, x) for x in ['spam', 'community', 'respected', 'base']],
            initial='community')
    tab = forms.CharField(required=False) # the rule tab to show
    rule = forms.CharField(required=False) # the string rule, overrides the tab in terms of rule

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.disable_csrf = True # not desirable for the scan form
        self.helper.layout = Layout(
                # NOTE We have a custom template to accomodate list.js needs with the "list" class
                # and adding an invisible span with actual option text (bootstrap moves the label
                # text to ::before, ::after)
                Row(Column(Field('scan_query', css_class='typeahead form-control-lg')),
                    Column(InlineCheckboxes('query_tags', css_class='list',
                        template='widgets/form_searchable_multiplechoicefield.html',
                        style='max-height: 100px')),
                    Column(InlineCheckboxes('query_sites', css_class='list',
                        template='widgets/form_searchable_multiplechoicefield.html',
                        style='max-height: 100px'))),
                Row(Column('minimal_level')),
                HTML('<button type="submit" id="search-button" class="btn btn-primary btn-lg">Search the index</button>'
                    '{% if can_scan %} '
                    '<button name="is_scan" id="scan-button" value="true" type="submit" class="btn btn-primary btn-lg">Scan the Web</button>'
                    '{% endif %}'))

python_modules/ascan/scan/views/dynamic.py
from datetime import datetime, timezone
from logging import debug, info
import random
import socket

from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from dynamic_preferences.registries import global_preferences_registry
from ipware import get_client_ip

from bg.models import QueryRecord
from scan.control import (maybe_issue_guest_scan_permission, request_scan, verify_scan_permission,
        maybe_give_feedback_tag_site_link)
from scan.forms import EditableScanForm
from scan.get_results import rules_results
from scan.utils import trust_level_to_numeric
from scan.models import Site, TagSiteLink, ResultRule
from manager.forms import SimpleCrawlForm

@staff_member_required
def crawl(request):
    form = SimpleCrawlForm(request.POST)
    context = { 'form': form }
    if form.is_valid():
        print(form.data)
        job = request_scan(request.user, '', query_tags=[],
                query_site_names=[form.cleaned_data['crawl_site'].site_name],
                is_simple_crawl=True,
                is_ip=False, is_privileged=True)
        context['start_ok'] = True
        context['job_id'] = job.id
        context['site_name'] = form.cleaned_data['crawl_site'].site_name
    return render(request, 'scan/crawl.html', context=context)

@csrf_exempt
def search(request):
    global_preferences = global_preferences_registry.manager()

    # Parse the form information to know what to search for.
    form = EditableScanForm(data=request.GET)
    if not form.is_valid():
        context = { 'with_errors': True, 'form': form }
        return render(request, 'scan/indexresults.html', context=context, status=400)

    # Unpacking the form data.
    scan_query = form.cleaned_data['scan_query']
    query_tags = [tag.name for tag in form.cleaned_data['query_tags']]
    explicit_site_names = [site.site_name for site in form.cleaned_data['query_sites']]
    minimal_level = trust_level_to_numeric(form.cleaned_data['minimal_level'])
    debug('query tags: {}, minimal level: {}'.format(query_tags, minimal_level))

    # Is an actual scan requested?
    if 'is_scan' in request.GET and request.GET['is_scan']:
        scan_performed = verify_scan_permission(request.user, get_client_ip(request)[0])
        # If the scan is being performed, check if it is finished and display progress information
        # if it's not.
        if scan_performed:
            debug('A scan will be performed.')
            job = request_scan((request.user if request.user.is_authenticated
                else get_client_ip(request)),
                scan_query, query_tags=query_tags, query_site_names=explicit_site_names,
                minimal_level=minimal_level,
                is_ip=not request.user.is_authenticated,
                is_privileged=request.user.is_staff)
            return redirect('/manager/scaninfo/?job_id={}'.format(job.id))
        # If the scan request just failed, flash the negative infomation.
        if not scan_performed:
            debug('A scan was requested and rejected.')
            messages.add_message(request, messages.WARNING,
                    'Sorry! We can\'t currently give you the resources to scan. Here\'s the index '
                    'results instead.')

    # The index-only search response (if there is no scan or it finished).
    # TODO KLUDGE currently unlimited scan permissions for registered
    if request.user.is_authenticated:
        can_scan = True
    else:
        can_scan = maybe_issue_guest_scan_permission(get_client_ip(request))
    query_site_names = explicit_site_names + [site.site_name
            for site in Site.objects.filter(
                tag_links__tag__in=form.cleaned_data['query_tags']).all()]
    context = { 'scan_phrase': scan_query, 'form': form, 'can_scan': can_scan,
            'sites': query_site_names, 'tags': query_tags }

    context['tabs'] = ResultRule.objects.filter(assigned_user_id__in=[-1]
            +([request.user.id] if request.user.is_authenticated else []))
    rules = ''
    if form.cleaned_data['rule']:
        rules = form.cleaned_data['rule']
        context['current_tab'] = settings.DEFAULT_RESULT_RULE['slug']
    elif form.cleaned_data['tab']:
        for rule in context['tabs']:
            if rule.slug == form.cleaned_data['tab']:
                context['current_tab'] = rule.slug
                rules = rule.rule_string
    else:
        context['current_tab'] = settings.DEFAULT_RESULT_RULE['slug']
        rules = settings.DEFAULT_RESULT_RULE['rule_string']

    try:
        context.update(rules_results(scan_query, rules, query_site_names=query_site_names,
            highlight=True))
    except socket.timeout:
        messages.add_message(request, messages.ERROR, 'Our server seems to be overloaded now.')
        context['with_errors'] = True
        return render(request, 'scan/indexresults.html', context=context, status=503)
    except Exception as e:
        info('Exception {} blocked getting a result from Solr: {}'.format(type(e).__name__, e))
        messages.add_message(request, messages.ERROR, 'We experienced an internal error.')
        context['with_errors'] = True
        return render(request, 'scan/indexresults.html', context=context, status=503)

    # Try to issue and add a feedback permission.
    if (random.random() < global_preferences['trust_levels__feedback_ask_frequency']):
        debug('Trying to issue a feedback permission...')
        site_names = list(set(doc['site_name'] for doc in context['result']))
        gradable_links = TagSiteLink.objects.filter(tag__name__in=query_tags,
                site__site_name__in=site_names, level__gte=minimal_level).all()
        debug('{} gradable tag-site links.'.format(len(gradable_links)))
        gradable_link = maybe_give_feedback_tag_site_link(
                (request.user if request.user.is_authenticated
                    else get_client_ip(request)),
                gradable_links,
                is_ip=not request.user.is_authenticated)
        debug('Gradable link maybe: {}'.format(gradable_link))
        if gradable_link:
            info('Issued permission for feedback on {} for {}/{}'.format(
                gradable_link, request.user, get_client_ip(request)))
            context['possible_feedback'] = {
                    'site': gradable_link.site.site_name,
                    'tag': gradable_link.tag.name
                    }

    # Make the query record if needed.
    if request.user.is_authenticated and request.user.userprofile.wants_query_records:
        try: # don't duplicate if possible
            existing_record = QueryRecord.objects.get(person=request.user, query_phrase=scan_query,
                    query_site_names=explicit_site_names, query_tags=query_tags,
                    minimal_level=form.cleaned_data['minimal_level'])
            existing_record.date_submitted = datetime.now(tz=timezone.utc)
            existing_record.save()
        except QueryRecord.DoesNotExist:
            QueryRecord.objects.create(person=request.user, query_phrase=scan_query,
                    query_site_names=explicit_site_names, query_tags=query_tags,
                    minimal_level=form.cleaned_data['minimal_level'])

    return render(request, 'scan/indexresults.html', context=context)

python_modules/ascan/scan/views/static.py
from django.shortcuts import render
from ipware import get_client_ip

from scan.control import maybe_issue_guest_scan_permission
from scan.forms import PublicScanForm

def index(request):
    form = PublicScanForm()
    # TODO KLUDGE currently unlimited scan permissions for registered
    if request.user.is_authenticated:
        can_scan = True
    else:
        can_scan = maybe_issue_guest_scan_permission(get_client_ip(request))
    return render(request, 'scan/home.html', context={ 'can_scan': can_scan, 'form': form })

python_modules/ascan/scan/templates/scan/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% block page_title %}{% endblock %} - ActualScan{% endblock %}</title>

{% block metas %}{% endblock %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block scripts %}{% endblock %}
<link rel="stylesheet" href="{% static 'css/scan.css' %}">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ActualScan</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
     aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">

        <div class="border-right mx-1"></div>
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
           <a class="nav-link" href="/accounts/logout/">Log out</a>
        </li>

        <div class="border-right mx-1"></div>
        <li class="nav-item">
           <span class="nav-link">My:</span>
        </li>

        <li class="nav-item active">
           <a class="nav-link" href="/bg/mysearches/">searches</a>
        </li>

        <li class="nav-item active">
           <a class="nav-link" href="/manager/rules/">rules</a>
        </li>

        <li class="nav-item active">
           <a class="nav-link" href="/manager/suggestions/">suggestions</a>
        </li>

        <li class="nav-item active">
           <a class="nav-link" href="/bg/userprofile/">account</a>
        </li>
        {% else %}
        <li class="nav-item active">
           <a class="nav-link" href="/accounts/login/">Log in</a>
        </li>

        <li class="nav-item active">
           <a class="nav-link text-primary" href="/bg/join/">Join for free</a>
        </li>
        {% endif %}

        <div class="border-right mx-1"></div>

        <li class="nav-item active">
           <a class="nav-link" href="/manager/sites/">Sites</a>
        </li>

        <li class="nav-item active">
           <a class="nav-link" href="/manager/tags/">Tags</a>
        </li>

        <li class="nav-item active">
           <a class="nav-link" href="/manager/scans/">Scans</a>
        </li>

        <div class="border-right mx-1"></div>

        {% if request.user.is_staff %}
        <li class="nav-item active">
           <a class="nav-link" href="/manager/decisions">Decisions</a>
        </li>

        <li class="nav-item active">
           <a class="nav-link" href="/admin/">Admin</a>
        </li>
        {% endif %}
     </ul>
  </div>
</nav>


{% block content %}
<div class="justify-content-center">
<main class="container-fluid">
{% block big_container %}
   <div class="col-lg-6 offset-lg-3 p-3">
   {% bootstrap_messages %}

   {% block container %}{% endblock %}
   </div>
{% endblock %}
 </main>
</div>

 <footer class="footer text-center">
   <div class="container">
     <ul class="list-inline">
       <li class="text-muted">Szymon Rutkowski &copy; 2020
       {% block footer %}{% endblock %}
     </ul>
   </div>
 </footer>
{% endblock %}
</body>
</html>

python_modules/ascan/scan/templates/scan/crawl.html
{% extends 'scan/base.html' %}
{% load bootstrap4 %}

{% block page_title %}Simple site crawl{% endblock %}

{% block container %}
{% if start_ok %}
<div class="alert alert-success">
   Crawling of the site <strong>{{ site_name }}</strong> should start shortly.
</div>
<div class="d-inline-block p-2">
   <a href="/manager/scaninfo/?job_id={{ job_id }}" class="btn btn-secondary">See the scan job</a>
</div>
{% else %}
<div class="alert alert-warning">
   We had a problem with starting the crawl of <strong>{{ site_name }}</strong>.
   Please contact the administration.
   {% if form.errors %}
   <ul>
      {% for field in form %}
      {% for error in field.errors %}
      <li>{{ field.label }}: {{ error|escape }}</li>
      {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
      <li>{{ error|escape }}</li>
      {% endfor %}
   </ul>
   {% endif %}
</div>
{% endif %}
<div class="d-inline-block p-2">
   <a href="/manager/scans/" class="btn btn-secondary">Return to the list of scans</a>
</div>
{% endblock %}

python_modules/ascan/scan/templates/scan/home.html
{% extends 'scan/base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load static %}

{% block page_title %}Search{% endblock %}

{% block scripts %}
<script type="application/javascript" src="{% static 'js/datepicker.min.js' %}"></script>
<script type="application/javascript" src="{% static 'js/list.min.js' %}"></script>
<script type="application/javascript" src="{% static 'js/typeahead.min.js' %}"></script>
<script type="application/javascript" src="{% static 'js/scanform.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/datepicker.min.css' %}">
<link rel="stylesheet" href="{% static 'css/typeaheadjs.css' %}"></script>
{% endblock %}

{% block container %}
<div class="text-center">
<img src="{% static 'logo1.png' %}" alt="ActualScan" style="width: 65%; margin: 40px">
</div>

<form action="/scan/search/">
   <dl>
   {% crispy form %}
   </dl>
</form>

<script defer type="application/javascript">
   var options = {
      valueNames: [ 'possible-choice' ]
   };

   var siteList = new List('query_sites-searchable', options)
   var tagList = new List('query_tags-searchable', options)

var suggestionsGetter = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  remote: {
    url: '/bg/sug/?q=%QUERY',
    wildcard: '%QUERY'
  }
})
$('#id_scan_query').typeahead(null,
   {
      name: 'query_phrase',
      source: suggestionsGetter
   })
</script>
{% endblock %}

python_modules/ascan/scan/templates/scan/indexresults.html
{% extends 'scan/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% load markdownify %}
{% load scan_extras %}

{% block page_title %}{% if scan_phrase %}{{ scan_phrase }}{% else %}Searching{% endif %}{% endblock %}

{% block scripts %}
<script type="application/javascript" src="{% static 'js/datepicker.min.js' %}"></script>
<script type="application/javascript" src="{% static 'js/list.min.js' %}"></script>
<script type="application/javascript" src="{% static 'js/typeahead.min.js' %}"></script>
<script type="application/javascript" src="{% static 'js/scanform.js' %}"></script>
<script type="application/javascript" src="{% static 'js/scoringrules.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/datepicker.min.css' %}">
<link rel="stylesheet" href="{% static 'css/typeaheadjs.css' %}"></script>
{% endblock %}

{% block big_container %}

<div class="text-center p-3 m-3 border border-dark" style='background-color: #f8f8f8'>
<form action="/scan/search/">
   <dl>
      {% crispy form %}
   </dl>
</form>
</div>

<script defer type="application/javascript">
   var options = {
      valueNames: [ 'possible-choice' ]
   };

   var siteList = new List('query_sites-searchable', options)
   var tagList = new List('query_tags-searchable', options)

var suggestionsGetter = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  remote: {
    url: '/bg/sug/?q=%QUERY',
    wildcard: '%QUERY'
  }
})
$('#id_scan_query').typeahead(null,
   {
      name: 'query_phrase',
      source: suggestionsGetter
   })
</script>

{% if possible_feedback %}
   <script type="text/javascript">
      window.FEEDBACK_SITE = '{{ possible_feedback.site }}'
      window.FEEDBACK_TAG = '{{ possible_feedback.tag }}'
   </script>
   <script type="application/javascript" src="{% static 'js/feedback_prompt.js' %}"></script>
{% endif %}
<script type="text/javascript">
   window.QUERY_PHRASE = '{{ scan_phrase }}'
   window.SITES = {% if sites %}{{ sites }}{% else %}[]{% endif %}
   window.TAGS = {% if tags %}{{ tags }}{% else %}[]{% endif %}
   window.RULES_STRING = '{{ rules_string }}'
   window.FEATURE_CODES = {
      {% for field_name, stats in field_stats.items %}
      '{{ field_name }}': '{{ stats.code }}',{% endfor %}
   }
</script>

{% bootstrap_messages %}
{% if with_errors %}
<div class="alert alert-danger" role="alert">
   <p>Sorry, we experienced a problem with your request.</p>
   {% if form.errors %}
   <ul>
      {% for field in form %}
      {% for error in field.errors %}
      <li>{{ field.label }}: {{ error|escape }}</li>
      {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
      <li>{{ error|escape }}</li>
      {% endfor %}
   </ul>
   {% endif %}
<noscript><a class="btn btn-primary mx-4" href="/">Go back</a></noscript>
<script>document.write('<a class="btn btn-primary align-middle mx-4" href="javascript:history.go(-1)">Go back</a>')</script>
{% if not form.errors %}
<a class="btn btn-primary mx-4" href="{{ request.path }}">Retry</a>
{% endif %}
</div>
{% endif %}
{% if not result %}
<div class="alert alert-primary" role="alert">
   Sorry, we did not find any results for your query.
   {% if scan_phrase and scan_phrase|phrase_generalizable %}
   You can also try <a href="/scan/search/?scan_query={{ scan_phrase|generalize_phrase }}&{% include "widgets/form_link.html" with repl_field="scan_query" %}">{{ scan_phrase|generalize_phrase }}</a>.
   {% endif %}
   <noscript><a class="btn btn-primary mx-4" href="/">Go back</a></noscript>
   <script>document.write('<a class="btn btn-primary align-middle mx-4" href="javascript:history.go(-1)">Go back</a>')</script>
</div>
{% elif scan_phrase and scan_phrase|phrase_generalizable and result|length < 10 %}
<div class="alert alert-primary" role="alert">
   You can also try <a href="/scan/search/?scan_query={{ scan_phrase|generalize_phrase }}&{% include "widgets/form_link.html" with repl_field="scan_query" %}">{{ scan_phrase|generalize_phrase }}</a>.
</div>
{% endif %}

<ul class="nav nav-tabs">
   {% for rule in tabs %}
   <li class="nav-item" style="background-color: {{ rule.slug|colorize_string }}">
      <a class="nav-link{% if rule.slug == current_tab %} active{% endif %}" href="/scan/search/?tab={{ rule.slug }}{% include "widgets/form_link.html" with repl_field="tab" repl_field2="rule" %}">
         {{ rule.name }}</a>
   </li>
   {% endfor %}
</ul>

<div class="row">

{% if result %}
<div class="col-sm card">
    <div id="main-results" class="list-group list-group-flush">
    {% for item in result %}
    <div class="list-group-item">
    <a href="{{ item.url }}" class="result-url">{{ item.url }}</a><br>
    <div class="card-text">
       <span class="result-text">
       {{ item.text_en | markdownify }}{{ item.text_xx | markdownify }}
       </span>
       <small class="text-muted">
          by <span class="result-author">{{ item.author }}</span>
          <span class="result-date">{% if item.date_post %}({{ item.date_post }}){% endif %}</span>
          at <span class="result-site">{{ item.site_name }}</span>
       </small>
    {% include "widgets/feedback_prompt.html" with site_name=item.domain %}
    </div>
    </div>
    {% endfor %}
    </div>
</div>
{% endif %}
{% if field_stats %}
<div class="col-sm card">
   <div class="list-group list-group-flush">
      <div id="results-status"></div>
      {% for field_name, stats in field_stats.items %}
      <div class="list-group-item d-flex justify-content-between">
         <div class="col-sm-6"><h5>{{ stats.full_name }}</h5></div>
         <div>
         {% if stats.kind == 'date' %}
            min
            <input name='{{ field_name }}_min' id='{{ field_name }}_min' type='text' oninput="updateScoringRules('{{ field_name }}')" min='{{ stats.min }}' value={% if rules.field_name %}'{{ rules.field_name.min}}'{% else %}'{{ stats.min }}'{% endif %} class="form-control"><br>
         max
         <input name='{{ field_name }}_max' id='{{ field_name }}_max' type='text' oninput="updateScoringRules('{{ field_name }}')" max='{{ stats.max }}' value={% if rules.field_name %}'{{ rules.field_name.max }}'{% else %}'{{ stats.max }}'{% endif %} class="form-control">
         {% else %}
            min
            <input id='{{ field_name }}_min' type='range' step='0.01' min='{{ stats.min }}' max='{{ stats.max }}' oninput="updateScoringRules('{{ field_name }}')" value={% if rules.field_name %}'{{ rules.field_name.min}}'{% else %}'{{ stats.min }}'{% endif %}>
         <value id='{{ field_name }}_min_val'>{% if rules.field_name %}{{ rules.field_name.min}}{% else %}{{ stats.min }}{% endif %}</value><br>
         max
         <input id='{{ field_name }}_max' type='range' step='0.01' min='{{ stats.min }}' max='{{ stats.max }}' oninput="updateScoringRules('{{ field_name }}')" value={% if rules.field_name %}'{{ rules.field_name.max }}'{% else %}'{{ stats.max }}'{% endif %}>
         <value id='{{ field_name }}_max_val'>{% if rules.field_name %}{{ rules.field_name.max }}{% else %}{{ stats.max }}{% endif %}</value><br>
         {% endif %}
         weight
         <input id='{{ field_name }}_weight' type='range' step='0.01' min='0' max='50' oninput="updateScoringRules('{{ field_name }}')" value={% if rules.field_name %}'{{ rules.field_name.weight }}'{% else %}'0'{% endif %}>
         <value id='{{ field_name }}_weight_val'>{% if rules.field_name %}{{ rules.field_name.weight }}{% else %}0{% endif %}</value>
         </div>
      </div>
      {% endfor %}
   </div>
   <div class="list-group-item d-flex justify-content-between">
      <form action="/manager/makerule/">
         <label for="custom_rules_code">Code:</label>
         <input id="rules_code" name="custom_rules_code" value="{{ rules_string }}" oninput="updateScoringRules('ALL')" autocomplete="off">
         <input type="submit" class="btn btn-secondary" value="Add this as a new rule">
      </form>
   </div>
</div>
{% endif %}

</div>
{% endblock %}